choco install autohotkey.portable
choco install docker-desktop
choco install DotNet4.5.2
choco install dotnet4.7.1
choco install dotnetfx
choco install Firefox
choco install git
choco install git.install
choco install google-drive-file-stream
choco install GoogleChrome
choco install iTunes
choco install sakuraeditor
choco install sourcetree
choco install teraterm
choco install virtualbox
choco install vscode
choco install winmerge
choco install zoom
 
choco install adobereader
choco install curl
choco install dbeaver
choco install docker-cli
choco install docker-desktop
choco install docker-machine
choco install docker-toolbox
choco install filezilla
choco install k3d
choco install kubernetes-cli
choco install kubernetes-helm
choco install Minikube
choco install openssh
choco install pyenv-win
choco install python
choco install python3
choco install sourcetree
choco install squid
choco install teraterm
choco install thunderbird
choco install virtualbox
choco install vlc
choco install vnc-viewer
choco install vscode
choco install vscode.install
choco install winmerge
choco install winscp
choco install winscp.install
choco install zoom
