choco install 1password8
choco install 7zip.install
choco install adobereader
choco install autohotkey.portable
choco install brave
choco install chocolatey
choco install chocolatey-compatibility.extension
choco install chocolatey-core.extension
choco install chocolatey-dotnetfx.extension
choco install chocolatey-windowsupdate.extension
choco install curl
choco install dbeaver
choco install docker-desktop
choco install DotNet4.5
choco install DotNet4.5.2
choco install dotnet4.7.1
choco install dotnet4.7.2
choco install dotnetfx
choco install Everything
choco install filezilla
choco install Firefox
choco install git
choco install git.install
choco install GoogleChrome
choco install google-chrome-x64
choco install googledrive
choco install google-drive-file-stream
choco install GoogleJapaneseInput
choco install iTunes
choco install kubernetes-cli
choco install kubernetes-helm
choco install lhaplus
choco install miniconda3
choco install Minikube
choco install netfx-4.7.2
choco install nodejs
choco install nodejs.install
choco install nvm
choco install nvm.install
choco install openssh
choco install packer
choco install PowerShell
choco install pyenv-win
choco install python
choco install python3
choco install python312
choco install python313
choco install sakuraeditor
choco install slack
choco install sourcetree
choco install squid
choco install steam
choco install teracopy
choco install teraterm
choco install vcredist140
choco install vcredist2015
choco install virtualbox
choco install vlc
choco install vlc.install
choco install vmware-powercli-psmodule
choco install vscode
choco install vscode.install
choco install winmerge
choco install winscp
choco install winscp.install
choco install zoom
